name: All News Journal

on:
  schedule:
    - cron: '15 10 * * *' # Roda às 07:15 Brasil (Foge do engarrafamento das 07:00)
  workflow_dispatch: # Botão manual

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15 # Dá mais tempo pro robô trabalhar se a rede estiver lenta

    steps:
    - name: Baixar código
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip' # Cache para instalar mais rápido na próxima

    - name: Instalar Dependências (Otimizado)
      run: |
        python -m pip install --upgrade pip
        python -m pip install "google-generativeai>=0.8.3" requests yfinance gspread feedparser google-auth oauth2client

    - name: Rodar Jornal
      env:
        GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        GCP_JSON: ${{ secrets.GCP_JSON }}
      run: python main.py
