name: Despertador do Site Premium

on:
  schedule:
    - cron: '*/15 * * * *' 
  workflow_dispatch:

jobs:
  wake_up:
    runs-on: ubuntu-latest
    steps:
    - name: Ping no Site (Simulando Chrome)
      run: |
        # Passando um User-Agent real para burlar o firewall do Streamlit
        # O timeout agora é de 60s para obrigar o script a esperar a máquina acordar
        curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" -sL --max-time 60 https://all-news-journal-w3utkdwxerflwqytjyc7p2.streamlit.app/ > /dev/null
        echo "Máquina forçada a acordar com sucesso."
